services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend2
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend2
    restart: unless-stopped
    ports:
      - "5173:80"      # nginx serves on 80, not 5173
    networks:
      - app-network
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo2
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: