import { existsSync, readFileSync } from "fs";
import path from "path";

const PROMPT_FILE_CANDIDATES = (fileName: string) => [
  path.resolve(__dirname, "../../../../prompts", fileName),
  path.resolve(__dirname, "../../prompts", fileName),
  path.resolve(process.cwd(), "prompts", fileName),
  path.resolve(process.cwd(), "../prompts", fileName),
];

const readPromptFile = (fileName: string) => {
  for (const candidate of PROMPT_FILE_CANDIDATES(fileName)) {
    if (existsSync(candidate)) {
      return readFileSync(candidate, "utf8");
    }
  }

  return null;
};

const extractPromptConstant = (source: string, constantName: string) => {
  const pattern = new RegExp(`${constantName}\\s*=\\s*"""([\\s\\S]*?)"""`);
  const match = source.match(pattern);
  return match?.[1]?.trim() ?? null;
};

const DEFAULT_ENHANCED_ATS_SYSTEM_PROMPT = [
  "You are an advanced ATS Resume Analyzer used in a production-level AI Resume Builder platform.",
  "The analysis must follow industry-standard hiring and resume screening practices, providing recruiter-grade analysis.",
  "",
  "CORE GOALS:",
  "1. Calculate a highly accurate ATS compatibility score out of 100 using the weighted formula below.",
  "2. Detect missing keywords, weak impact statements, formatting issues, parsing issues, section problems, poor metric usage, weak action verbs.",
  "3. Identify sections that are missing, empty, or contain placeholder text and tell the user to fix them.",
  "4. Every suggestion must specify the section, explain WHY it hurts the ATS score, and describe what to improve.",
  "5. Rank suggestions by score impact — highest potential gain first.",
  "6. Align every suggestion with one of the 5 ATS scoring categories and state which category it improves.",
  "",
  "ATS SCORING CATEGORIES (weighted):",
  "1. KEYWORD_MATCH (30%): Role-specific keywords, hard skills, technologies, frameworks, keyword density.",
  "2. RESUME_STRUCTURE_PARSING (20%): ATS-readable formatting, proper headings, parsing compatibility, section organization.",
  "3. CONTENT_QUALITY (25%): Quantified achievements, measurable impact, clarity, strong bullet points, action-oriented language.",
  "4. EXPERIENCE_RELEVANCE (15%): Project relevance, experience alignment, domain alignment, technical depth.",
  "5. FORMATTING_CONSISTENCY (10%): Font consistency, spacing, date formatting, capitalization, readability.",
  "",
  "WEIGHTED FORMULA:",
  "overallScore = (keywordMatch * 0.30) + (parsing * 0.20) + (contentQuality * 0.25) + (experienceRelevance * 0.15) + (formatting * 0.10)",
  "",
  "RECRUITER-GRADE ANALYSIS APPROACH:",
  "- Simulate the 6-second resume scan: assess first impression, formatting clarity, role relevance.",
  "- Apply keyword matching with density analysis: check keyword frequency, placement, and suggested minimums.",
  "- Evaluate bullet quality: strong action verbs, quantified impact, leadership signals, passive voice detection.",
  "- Score technical depth for projects: assess links, deployment, GitHub, measurable impact.",
  "- Categorize skills and detect redundancies, outdated technologies, and modern alternatives.",
  "- Check industry-specific requirements and compliance.",
  "- Generate prioritized recommendations (P0-P3) based on expected impact and effort.",
  "",
  "SECTION-SPECIFIC ANALYSIS INSTRUCTIONS:",
  "- sectionWiseAnalysis: For each section (summary, experience, skills, education, projects, certifications, languages, awards, publications, references), check if present, empty, or placeholder. Score each section across 5 dimensions (atsScore, qualityScore, completenessScore, keywordRelevanceScore, recruiterEffectivenessScore). List strengths, weaknesses, suggestions, and missing elements.",
  "- experienceAnalysis: Count entries and bullets. Calculate strong verb ratio, quantified ratio, leadership ratio. Detect generic bullets and passive voice. Compute average bullet length. List top action verbs and weak verbs.",
  "- projectsAnalysis: Count entries. Check for deployment links, GitHub links, and technical depth. Detect tutorial-level projects. List technologies used and measurable impact.",
  "- skillsAnalysis: Count total skills, categorize by relevance (high/medium/low). Detect redundant, outdated, and missing critical skills. Suggest modern alternatives for each outdated technology.",
  "- roleMatchAnalysis: Calculate match percentage against target role. List matched, missing, and weak keywords. Assess experience level match and suggest alternative roles.",
  "- keywordDensity: Track each keyword's frequency and density in the resume. Flag overused or underused keywords against suggested minimum counts.",
  "- contentQualityAnalysis: Score clarity, conciseness, impact, professionalism, and grammar quality. List specific issues found in the text.",
  "- recruiterFeedback: Provide simulated recruiter first impression, shortlisting probability, technical credibility, leadership impression, and resume professionalism. List strengths and concerns from a hiring manager perspective.",
  "- industryChecks: Run industry-specific validation checks (e.g., tech, finance, healthcare, academia) with pass/fail status, importance level, and details.",
  "- warnings: Flag missing sections, empty sections, placeholder content, formatting issues, and critical gaps with severity levels (warning, error, info).",
  "- recommendations: Generate prioritized recommendations (P0-P3) with category (content, formatting, keyword, structure, skills), expected impact description, and effort level (low, medium, high).",
  "",
  "SCORING DETAILS FOR SECTION-WISE ANALYSIS:",
  "- atsScore (0-100): How well the section is optimized for ATS parsing.",
  "- qualityScore (0-100): Quality of the content in this section.",
  "- completenessScore (0-100): How complete and thorough the section is.",
  "- keywordRelevanceScore (0-100): Relevance of keywords present in the section.",
  "- recruiterEffectivenessScore (0-100): How effective the section is at impressing a recruiter.",
  "",
  "EXPERIENCE ANALYSIS SCORING:",
  "- strongVerbRatio: Proportion of bullets starting with strong action verbs (achieved, built, designed, implemented, etc.) vs weak verbs (was, were, has, had, been).",
  "- quantifiedRatio: Proportion of bullets containing numbers, percentages, or metrics.",
  "- leadershipRatio: Proportion of bullets mentioning team leadership, mentoring, or cross-functional collaboration.",
  "- genericBulletCount: Number of bullets with generic, non-specific content that lack impact.",
  "- passiveVoiceCount: Number of bullets written in passive voice (was responsible for, was tasked with).",
  "- averageBulletLength: Average word count per bullet.",
  "",
  "PROJECTS ANALYSIS SCORING:",
  "- technicalDepthScore (0-100): How technically deep and sophisticated the project work is.",
  "- hasMeasurableImpact: Whether projects include metrics, outcomes, or measurable results.",
  "- isTutorialLevel: Whether projects appear to be basic tutorials rather than original work.",
  "",
  "SKILLS ANALYSIS SCORING:",
  "- categorizationScore (0-100): How well skills are organized and categorized.",
  "- relevance: Each categorized group is marked as 'high', 'medium', or 'low' relevance to the target role.",
  "",
  "CONTENT QUALITY ANALYSIS SCORING:",
  "- clarityScore (0-100): How clear and easy to understand the content is.",
  "- concisenessScore (0-100): How concise and to-the-point the content is without fluff.",
  "- impactScore (0-100): How impactful and achievement-oriented the content is.",
  "- professionalismScore (0-100): Professional tone, language, and presentation.",
  "- grammarQuality (0-100): Grammar, spelling, punctuation, and sentence structure quality.",
  "",
  "ROLE MATCH ANALYSIS:",
  "- matchPercentage (0-100): Overall match between resume and target role.",
  "- experienceLevelMatch: 'entry', 'mid', 'senior', or 'lead'.",
  "- industryFit: Description of which industries the resume best fits.",
  "",
  "RECRUITER FEEDBACK SCORING:",
  "- shortlistingProbability (0-100): Likelihood of being shortlisted for an interview.",
  "- technicalCredibility: 'low', 'medium', or 'high'.",
  "- leadershipImpression: 'low', 'medium', or 'high'.",
  "- resumeProfessionalism: 'low', 'medium', or 'high'.",
  "- clarityScore (0-100): Overall clarity of the resume from a recruiter perspective.",
  "",
  "IMPORTANT RULES:",
  "- Never invent experience, employers, tools, years, or degrees — if a section is missing or empty, suggest filling it with real entries, do NOT create fake ones.",
  "- Detect weak bullets like 'responsible for', 'worked on', 'helped with' and suggest stronger rewrites.",
  "- Detect ATS-unfriendly formatting (tables, icons, multi-column, images, progress bars, unusual symbols).",
  "- Provide semantic keyword recommendations based on target job role, tech stack, and experience level.",
  "- Explain WHY each issue affects ATS systems.",
  "- Prioritize high-impact fixes first.",
  "- Simulate realistic recruiter behavior: first 6-second scan, keyword filtering, relevance ranking.",
  "- Output valid JSON only.",
].join("\n");

const DEFAULT_ENHANCED_ATS_SCORING_PROMPT = [
  "TASK: Comprehensive ATS score analysis with detailed section-wise improvement suggestions and recruiter-grade feedback.",
  "",
  "INPUTS:",
  "- RESUME_TEXT: {resume_text}",
  "- JOB_DESCRIPTION: {job_description}",
  "- ROLE_TITLE: {role_title}",
  "",
  "OUTPUT REQUIREMENTS:",
  "1) Output valid JSON only (no markdown).",
  "2) Score each of the 5 weighted categories 0-100 (keywordMatch, parsing, contentQuality, experienceRelevance, formatting), then compute overallScore using the weighted formula.",
  "3) If JOB_DESCRIPTION is empty, infer target role keywords from resume and still provide improvement suggestions.",
  "4) Never hallucinate fake experience. Only suggest filling empty or weak sections.",
  "5) If a section is missing or empty, flag it and suggest what content to add.",
  "6) Order suggestions by importance — highest impact first.",
  "7) Each suggestion must reference which ATS category it improves (keywordMatch, parsing, contentQuality, experienceRelevance, formatting).",
  "8) Populate ALL sections in the JSON schema below. If data is not available, use sensible defaults (empty arrays, 0 scores, null strings).",
  "",
  "RETURN THIS EXACT JSON SCHEMA:",
  "{",
  '   "overallScore": 0,',
  '   "summary": {',
  '      "strengths": ["3-5 key strengths"],',
  '      "weaknesses": ["3-5 critical weaknesses"],',
  '      "industryReadiness": "one-line assessment",',
  '      "recruiterImpression": "6-second scan verdict"',
  "   },",
  '   "sectionWiseAnalysis": [',
  "      {",
  '         "section": "summary",',
  '         "label": "Summary",',
  '         "scores": {',
  '            "atsScore": 0,',
  '            "qualityScore": 0,',
  '            "completenessScore": 0,',
  '            "keywordRelevanceScore": 0,',
  '            "recruiterEffectivenessScore": 0',
  "         },",
  '         "isPresent": true,',
  '         "isEmpty": false,',
  '         "isPlaceholder": false,',
  '         "wordCount": 0,',
  '         "bulletCount": 0,',
  '         "strengths": [],',
  '         "weaknesses": [],',
  '         "suggestions": [],',
  '         "missingElements": []',
  "      }",
  "   ],",
  '   "categoryScores": {',
  '      "keywordMatch": 0,',
  '      "parsing": 0,',
  '      "contentQuality": 0,',
  '      "experienceRelevance": 0,',
  '      "formatting": 0',
  "   },",
  '   "missingKeywords": [',
  "      {",
  '         "keyword": "term",',
  '         "importance": "high|medium|low",',
  '         "reason": "why it is needed",',
  '         "suggestedPlacement": "summary|skills|experience|projects"',
  "      }",
  "   ],",
  '   "formatIssues": [',
  "      {",
  '         "id": "fmt-1",',
  '         "severity": "high|medium|low",',
  '         "section": "section name",',
  '         "problem": "what is wrong",',
  '         "reason": "why it hurts ATS",',
  '         "fixSuggestion": "how to fix it"',
  "      }",
  "   ],",
  '   "sectionAnalysis": [',
  "      {",
  '         "section": "section name",',
  '         "score": 0,',
  '         "issues": ["issue 1", "issue 2"],',
  '         "recommendations": ["rec 1", "rec 2"]',
  "      }",
  "   ],",
  '   "experienceAnalysis": {',
  '      "entryCount": 0,',
  '      "totalBullets": 0,',
  '      "strongVerbRatio": 0,',
  '      "quantifiedRatio": 0,',
  '      "leadershipRatio": 0,',
  '      "genericBulletCount": 0,',
  '      "passiveVoiceCount": 0,',
  '      "averageBulletLength": 0,',
  '      "topActionVerbs": [],',
  '      "weakVerbsDetected": [],',
  '      "missingElements": [],',
  '      "suggestions": []',
  "   },",
  '   "projectsAnalysis": {',
  '      "entryCount": 0,',
  '      "hasLinks": false,',
  '      "hasDeploymentLinks": false,',
  '      "hasGithubLinks": false,',
  '      "technicalDepthScore": 0,',
  '      "hasMeasurableImpact": false,',
  '      "isTutorialLevel": false,',
  '      "technologiesUsed": [],',
  '      "missingElements": [],',
  '      "suggestions": []',
  "   },",
  '   "skillsAnalysis": {',
  '      "totalSkills": 0,',
  '      "categorized": [',
  "         {",
  '            "category": "",',
  '            "skills": [],',
  '            "relevance": "high",',
  '            "isOutdated": false,',
  '            "suggestions": []',
  "         }",
  '      ],',
  '      "redundantSkills": [],',
  '      "outdatedTechnologies": [],',
  '      "modernAlternatives": [',
  "         {",
  '            "old": "",',
  '            "modern": ""',
  "         }",
  '      ],',
  '      "missingCriticalSkills": [],',
  '      "categorizationScore": 0,',
  '      "suggestions": []',
  "   },",
  '   "roleMatchAnalysis": {',
  '      "roleTitle": "",',
  '      "matchPercentage": 0,',
  '      "matchedKeywords": [],',
  '      "missingKeywords": [],',
  '      "weakKeywords": [],',
  '      "experienceLevelMatch": "mid",',
  '      "suggestedRoles": [],',
  '      "industryFit": "",',
  '      "suggestions": []',
  "   },",
  '   "keywordDensity": [',
  "      {",
  '         "keyword": "",',
  '         "count": 0,',
  '         "density": 0,',
  '         "suggestedMinCount": 0,',
  '         "status": "good"',
  "      }",
  "   ],",
  '   "contentQualityAnalysis": {',
  '      "overallQuality": "average",',
  '      "clarityScore": 0,',
  '      "concisenessScore": 0,',
  '      "impactScore": 0,',
  '      "professionalismScore": 0,',
  '      "grammarQuality": 0,',
  '      "issues": [],',
  '      "suggestions": []',
  "   },",
  '   "recruiterFeedback": {',
  '      "firstImpression": "",',
  '      "shortlistingProbability": 0,',
  '      "technicalCredibility": "medium",',
  '      "leadershipImpression": "medium",',
  '      "resumeProfessionalism": "medium",',
  '      "clarityScore": 0,',
  '      "detailFeedback": "",',
  '      "strengths": [],',
  '      "concerns": []',
  "   },",
  '   "industryChecks": [',
  "      {",
  '         "industry": "",',
  '         "checks": [',
  "            {",
  '               "name": "",',
  '               "passed": true,',
  '               "importance": "critical",',
  '               "details": ""',
  "            }",
  "         ]",
  "      }",
  "   ],",
  '   "warnings": [',
  "      {",
  '         "type": "missing_section",',
  '         "severity": "warning",',
  '         "section": "summary",',
  '         "message": "",',
  '         "suggestion": ""',
  "      }",
  "   ],",
  '   "recommendations": [',
  "      {",
  '         "priority": "P0",',
  '         "category": "content",',
  '         "title": "",',
  '         "description": "",',
  '         "expectedImpact": "",',
  '         "effort": "medium"',
  "      }",
  "   ],",
  '   "priorityFixes": [',
  "      {",
  '         "priority": 1,',
  '         "issue": "what to fix",',
  '         "expectedScoreIncrease": 0,',
  '         "atsCategory": "keywordMatch|parsing|contentQuality|experienceRelevance|formatting"',
  "      }",
  "   ],",
  '   "jd_keywords": {',
  '      "matched": [],',
  '      "missing": [],',
  '      "weak": []',
  "   },",
  '   "rewriteSuggestions": [',
  "      {",
  '         "id": "rs-1",',
  '         "section": "experience",',
  '         "original": "",',
  '         "suggested": "",',
  '         "reason": "",',
  '         "atsCategory": "contentQuality"',
  "      }",
  "   ],",
  '   "perSectionSuggestions": {',
  '      "summary": [],',
  '      "experience": [],',
  '      "skills": [],',
  '      "education": [],',
  '      "projects": []',
  "   },",
  '   "actionPlan": [',
  "      {",
  '         "step": 1,',
  '         "action": "",',
  '         "section": "",',
  '         "expectedImpact": "",',
  '         "effort": "low"',
  "      }",
  "   ],",
  '   "quickWins": [',
  "      {",
  '         "issue": "",',
  '         "fix": "",',
  '         "scoreGain": 0',
  "      }",
  "   ],",
  '   "sectionAudit": [',
  "      {",
  '         "section": "",',
  '         "status": "present|missing|empty|placeholder",',
  '         "issues": [],',
  '         "wordCount": 0',
  "      }",
  "   ],",
  '   "keywordPlacement": {',
  '      "summary": [],',
  '      "skills": [],',
  '      "experience": [],',
  '      "projects": [],',
  '      "education": []',
  "   },",
  '   "questionsForUser": [',
  "      {",
  '         "question": "",',
  '         "context": "",',
  '         "suggestedAnswer": ""',
  "      }",
  "   ],",
  '   "old_format_fields_for_backward_compat": {',
  '      "section_scores": { "summary": 0, "experience": 0, "skills": 0, "education": 0, "projects": 0, "formatting": 0 },',
  '      "quick_wins": [],',
  '      "section_audit": [],',
  '      "formatting_fixes": [],',
  '      "keyword_analysis": { "matched_keywords": [], "missing_keywords": [] }',
  "   }",
  "}",
].join("\n");

const DEFAULT_ENHANCED_ATS_RESCORE_PROMPT = [
  "Re-analyze the updated resume and return JSON only with before/after score comparison, implemented items, missed items, and next best actions.",
  "Previous score: {previous_score}. Updated resume: {updated_resume}. Job description: {job_description}.",
].join("\n");

const enhancedPromptSource = readPromptFile("enhanced_ats_prompt.py");

if (!enhancedPromptSource) {
  console.warn("[backend] ATS prompt template file not found: enhanced_ats_prompt.py. Using built-in fallback prompts.");
}

export const ENHANCED_ATS_SYSTEM_PROMPT = enhancedPromptSource
  ? (extractPromptConstant(enhancedPromptSource, "ENHANCED_ATS_SYSTEM_PROMPT") ?? DEFAULT_ENHANCED_ATS_SYSTEM_PROMPT)
  : DEFAULT_ENHANCED_ATS_SYSTEM_PROMPT;

export const ENHANCED_ATS_SCORING_PROMPT = enhancedPromptSource
  ? (extractPromptConstant(enhancedPromptSource, "ENHANCED_ATS_SCORING_PROMPT") ?? DEFAULT_ENHANCED_ATS_SCORING_PROMPT)
  : DEFAULT_ENHANCED_ATS_SCORING_PROMPT;

export const ENHANCED_ATS_RESCORE_PROMPT = enhancedPromptSource
  ? (extractPromptConstant(enhancedPromptSource, "ENHANCED_ATS_RESCORE_PROMPT") ?? DEFAULT_ENHANCED_ATS_RESCORE_PROMPT)
  : DEFAULT_ENHANCED_ATS_RESCORE_PROMPT;

export const buildEnhancedAtsUserPrompt = (resumeText: string, jobDescription: string, roleTitle: string = "") =>
  ENHANCED_ATS_SCORING_PROMPT
    .replace("{resume_text}", resumeText)
    .replace("{job_description}", jobDescription)
    .replace("{role_title}", roleTitle);
