import { TemplateMeta } from "@/types/resume-types";

export const TEMPLATES: TemplateMeta[] = [
  { id: "classic", name: "Classic", tag: "Timeless", category: "Professional", audience: "non-tech", description: "Timeless serif layout trusted by finance, law and academia.", isPremium: false, accent: "#1a1a1a", palette: { bg: "#FAF8F5", primary: "#1a1a1a", secondary: "#555555" } },
  { id: "executive", name: "Executive", tag: "Corporate", category: "Corporate", audience: "non-tech", description: "Navy header bar with strong hierarchy for leadership roles.", isPremium: false, accent: "#1B2B4B", palette: { bg: "#EEF1F7", primary: "#1B2B4B", secondary: "#3A5A8A" } },
  { id: "modern", name: "Modern", tag: "Tech-Ready", category: "Technical", audience: "tech", description: "Teal accent rule and skill chips built for tech startups.", isPremium: false, accent: "#0F766E", palette: { bg: "#F0FDFB", primary: "#0F766E", secondary: "#134E4A" } },
  { id: "compact", name: "Compact", tag: "One-Page", category: "Senior", audience: "non-tech", description: "Information-dense label-column layout for senior candidates.", isPremium: true, accent: "#111111", palette: { bg: "#F8F8F8", primary: "#111111", secondary: "#444444" } },
  { id: "sidebar", name: "Sidebar", tag: "Structured", category: "Creative", audience: "tech", description: "Dark sidebar with two-column structure, striking and scannable.", isPremium: true, accent: "#1E293B", palette: { bg: "#ffffff", primary: "#1E293B", secondary: "#94A3B8", sidebar: "#1E293B" } },
  { id: "scholarly", name: "Scholarly", tag: "Academic", category: "Academic", audience: "non-tech", description: "Centered academic layout with classic headings and balanced spacing.", isPremium: false, accent: "#1a1a1a", palette: { bg: "#ffffff", primary: "#1a1a1a", secondary: "#4a4a4a" } },
  { id: "research", name: "Research", tag: "Detailed", category: "Academic", audience: "non-tech", description: "Publication-style hierarchy tuned for research-heavy resumes.", isPremium: false, accent: "#1f1f1f", palette: { bg: "#ffffff", primary: "#1f1f1f", secondary: "#555555" } },
  { id: "administrative", name: "Administrative", tag: "Office", category: "Professional", audience: "non-tech", description: "Straightforward ATS-safe layout for office, coordination, and support roles.", isPremium: false, accent: "#374151", palette: { bg: "#ffffff", primary: "#374151", secondary: "#6B7280" } },
  { id: "operations", name: "Operations", tag: "Process", category: "Corporate", audience: "non-tech", description: "Balanced one-page template for operations, logistics, and program delivery roles.", isPremium: false, accent: "#0F4C5C", palette: { bg: "#F7FBFC", primary: "#0F4C5C", secondary: "#52707A" } },
  { id: "customer-service", name: "Customer Service", tag: "Service", category: "Professional", audience: "non-tech", description: "Friendly, high-clarity layout for service, support, and client-facing applications.", isPremium: false, accent: "#1D4ED8", palette: { bg: "#F8FAFC", primary: "#1D4ED8", secondary: "#64748B" } },
  { id: "healthcare", name: "Healthcare", tag: "Care", category: "Professional", audience: "non-tech", description: "ATS-friendly resume tuned for patient care, clinic, and allied health roles.", isPremium: true, accent: "#0F766E", palette: { bg: "#F5FBFA", primary: "#0F766E", secondary: "#5B7C78" } },
  { id: "education", name: "Education", tag: "Teaching", category: "Academic", audience: "non-tech", description: "Clean academic-adjacent layout for teaching, counseling, and campus support roles.", isPremium: true, accent: "#7C2D12", palette: { bg: "#FFFCFA", primary: "#7C2D12", secondary: "#78716C" } },
];
